#!/usr/bin/env bash


prefix="package_$2"

if [[ "package_kz_kafka_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kz_kafka_volume
	fi
	
if [[ "package_kz_zookeeper_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kz_zookeeper_volume
	fi
	
